packages:
  - .
  - ./platform
  - ./example/client

allowBuilds:
  esbuild: false
  protobufjs: false
  sharp: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes

minimumReleaseAgeExclude:
  - '@ai-sdk/provider-utils@3.0.98'

overrides:
  '@ai-sdk/provider-utils@<=3.0.97': ^3.0.98
  '@ai-sdk/provider-utils@<=3.0.98': ^4
  '@opentelemetry/core@<2.8.0': ^2.8.0
  chokidar: '>=5'
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  eslint-import-resolver-typescript: '^4.4.5'
  js-yaml@<=4.1.1: ^4.1.2
  markdown-it@<=14.1.1: ^14.1.2
  postcss@<8.5.10: ^8.5.10
  semver: '>=7'
  shell-quote: '>=1.8.4'

trustPolicy: no-downgrade
