packages:
  - .
  - ./platform
  - ./example/client

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  '@eslint/js': ^9
  '@stylistic/eslint-plugin': '>=5.0.0'
  '@types/react': '>=19.2.2'
  '@types/react-dom': '>=19.2.2'
  axios@=1.10.0: '>=1.11.0'
  eslint: ^9
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  jsondiffpatch@<0.7.2: '>=0.7.2'
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'
