packages:
  - .
  - ./platform
  - ./example/client

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

overrides:
  axios@=1.10.0: '>=1.11.0'
  jsondiffpatch@<0.7.2: '>=0.7.2'
